In [1]:
import numpy as np

In [5]:
A = np.array([[1, 2, 3], [4, 5,6], [7, 8, 9]])
B = np.array([[1, 2, 0], [3, 4,2], [4, 7, 8]])
print("A=")
print(A)
print("B=")
print(B)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B=
[[1 2 0]
 [3 4 2]
 [4 7 8]]


In [6]:
print ("Addition of two matrices: ")
print (np.add(A,B))

Addition of two matrices: 
[[ 2  4  3]
 [ 7  9  8]
 [11 15 17]]


In [8]:
print ("Subtraction of two matrices : ")
print (np.subtract(A,B))

Subtraction of two matrices : 
[[0 0 3]
 [1 1 4]
 [3 1 1]]


In [10]:
print ("Multiplication of two matrices: ")
print (np.multiply(A,B))

Multiplication of two matrices: 
[[ 1  4  0]
 [12 20 12]
 [28 56 72]]


In [12]:
print ("Matrix Division : ")
print (np.divide(A,B))

Matrix Division : 
[[1.         1.                inf]
 [1.33333333 1.25       3.        ]
 [1.75       1.14285714 1.125     ]]


<ipython-input-12-5f50083d903a>:2: RuntimeWarning: divide by zero encountered in true_divide
  print (np.divide(A,B))


In [14]:
print ("Matrix transposition : ")
print("A^T=")
print (A.T)
print("B^T=")
print (B.T)

Matrix transposition : 
A^T=
[[1 4 7]
 [2 5 8]
 [3 6 9]]
B^T=
[[1 3 4]
 [2 4 7]
 [0 2 8]]


In [26]:
#matrix multiplication
print ("The product of two matrices : ")
print (np.dot(A,B))
print("B*A")
print (np.dot(B,A))

The product of two matrices : 
[[ 19  31  28]
 [ 43  70  58]
 [ 67 109  88]]
B*A
[[  9  12  15]
 [ 33  42  51]
 [ 88 107 126]]


In [25]:
print("\nAfter removing the last column from the matrix A:\n",A[:,:-1])


After removing the last column from the matrix A:
 [[1 2]
 [4 5]
 [7 8]]


In [17]:
print("\n section of A:\n",A[1:,1:])


 section of A:
 [[5 6]
 [8 9]]
