In [1]:
#import required libraries
import numpy as np

In [3]:
# Define input features
X = np.array([[0,0],[0,1],[1,0],[1,1]])
print(X)

#Define target outputs
#Implementation of XOR gate
Y_target = np.array([[0],[0],[0],[1]])

#Assign Random weights
#6 for hidden layer
#3 for output layer
W1 = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
W2 = np.array([[0.7],[0.8],[0.9]])
print(W1)
print(W2)

#Learning rate
lr=0.05

# Define activation function - Sigmoid function
def sigmoid(x):
  return 1/(1+np.exp(-x))

#Define derivative of Activation Function - derivative of sigmoid Function
def der_sigmoid(x):
  return sigmoid(x)*(1-sigmoid(x))
  

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
[[0.7]
 [0.8]
 [0.9]]


In [4]:
for epoch in range(20000):
  #Forward propagation
  Z = np.dot(X,W1)
  H = sigmoid(Z)
  U = np.dot(H,W2)
  Y=sigmoid(U)
  E=Y-Y_target
  # Calculate Loss function (Mean Square error loss)
  L=1/2*(np.power(E,2))
  #print(output_error.sum())
  #print(output_error)

  # Backpropagation - Stage 1
  dL_dY=Y-Y_target
  dY_dU=Y*(1-Y)
  dU_dW2=H
  #print(dL_dY)
  #print(dY_dU)
  #print(dU_dW2)

  dL_dW2=np.dot(dU_dW2.T,dL_dY*dY_dU)
  

  #Weight updates in stage 1

  W2 -= lr*dL_dW2
  #print(weight_output)

  # Backpropagation - Stage 2
  dL_dY=Y-Y_target
  dY_dU=Y*(1-Y)
  dU_dH=W2
  dH_dZ=H*(1-H)
  dZ_dW1=X 
  
  dL_dH=np.dot(dL_dY*dY_dU,dU_dH.T)
  dL_dW1=np.dot(dZ_dW1.T,dH_dZ*dL_dH)

  #Weight updates in stage 2

  W1 -= lr*dL_dW1
  #print(weight_hidden)
print("W2=",W2)
print("W1=",W1)

W2= [[-7.65164598]
 [-7.61737179]
 [ 3.90325132]]
W1= [[ 1.01707804 -4.47053146  0.50334254]
 [-3.88883489  1.55940252  1.80528523]]


In [5]:
#Testing input data point
point=np.array([0,0])
z=np.dot(point,W1)
h=sigmoid(z)
op=np.dot(h,W2)
y_cap=sigmoid(op)
print(y_cap)


[0.00339218]


In [6]:
#Testing input data point
point=np.array([0,1])
z=np.dot(point,W1)
h=sigmoid(z)
op=np.dot(h,W2)
y_cap=sigmoid(op)
print(y_cap)


[0.04329776]


In [7]:
#Testing input data point
point=np.array([1,0])
z=np.dot(point,W1)
h=sigmoid(z)
op=np.dot(h,W2)
y_cap=sigmoid(op)
print(y_cap)

[0.03651343]


In [8]:
#Testing input data point
point=np.array([1,1])
z=np.dot(point,W1)
h=sigmoid(z)
op=np.dot(h,W2)
y_cap=sigmoid(op)
print(y_cap)

[0.93976475]
